import type { Metadata } from 'next';
import { Header } from '@/shared/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='min-h-screen'>
      <Header hasSearch={false} hasMenu={false} />
      {children}
    </main>
  );
}
