import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { AuthModalProvider, Header, Providers } from '@/shared/components';

import { StoreProvider } from '@/shared/components/store-provider';

const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body className={`${nunito.className}  antialiased`}>
        <StoreProvider>
          <Header />
          {children}
          <Providers />
          <AuthModalProvider />
        </StoreProvider>
      </body>
    </html>
  );
}
